version: '3.8'

services:
  # 1. The Database
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: winnow
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: winnow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    container_name: winnow-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # The beautiful Web UI
      - "1025:1025" # The SMTP port your C# app will send mail to
    environment:
      - MP_MAX_MESSAGES=500

  # LocalStack for SQS
  localstack:
    image: localstack/localstack:latest
    container_name: winnow-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

  # 3. The "Bouncer" (Virus & File Check)
  # bouncer:
  #   build:
  #     context: ./src/Services/Winnow.Bouncer # Folder containing the Go Dockerfile
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - localstack
  #   environment:
  #     AWS_ACCESS_KEY_ID: minioadmin
  #     AWS_SECRET_ACCESS_KEY: minioadmin
  #     S3_ENDPOINT: http://localstack:4566
  #     S3_BUCKET: winnow-quarantine

  # # 4. Your .NET API
  # api:
  #   build:
  #     context: ./src/Services/Winnow.Server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:8080" # Maps localhost:5000 to container:8080
  #   depends_on:
  #     - postgres
  #     - localstack
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Database=winnow_db;Username=winnow;Password=localpassword
  #     - AWS_ACCESS_KEY_ID=minioadmin
  #     - AWS_SECRET_ACCESS_KEY=minioadmin
  #     - S3_ServiceURL=http://localstack:4566
  #     - S3_ForcePathStyle=true

volumes:
  postgres_data: